spring:
  application:
    name: marky

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2-korean
          temperature: 0.1
      embedding:
        options:
          model: nomic-embed-text
          keep-alive: 5m

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        table-name: vector_store
        initialize-schema: false

