spring:
  application:
    name: marky

  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2-korean
          temperature: 0.1

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
